export interface SeedProductDef {
  id: string;
  slug: string;
  name: string;
  category: string;
  priceInr: number;
  priceUsd: number;
  backQuote: string;
  frontLogo: string;
  fabricGsm: number;
  fabricType: string;
  fit: string;
  sleeveType: string;
  color: string;
  description: string;
}

export const SIZES = ['S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'] as const;

export const SEED_PRODUCTS: SeedProductDef[] = [
  {
    id: 'prod_pink_sunfade_ombre_tee',
    slug: 'pink-sunfade-ombre-wash-boxy-fit-tshirt',
    name: 'The Pink Sunfade Ombre Boxy Tee',
    category: 'Tees',
    priceInr: 1699,
    priceUsd: 22,
    backQuote: 'NOT FOR EVERYONE.',
    frontLogo: 'MENANCE®',
    fabricGsm: 240,
    fabricType: '100% French Terry Cotton',
    fit: 'Boxy Fit',
    sleeveType: 'Half Sleeve',
    color: 'Pink Ombre',
    description: '240 GSM 100% French terry cotton heavy boxy fit tee with an artisanal pink sunfade ombre wash gradient. Features an architectural drape, thick crew rib collar, dropped shoulders, and ultra-soft brushed finish.',
  },
  {
    id: 'prod_henley_black',
    slug: 'the-henley-black',
    name: 'The Henley — Black',
    category: 'Henleys',
    priceInr: 1899,
    priceUsd: 24,
    backQuote: 'MIND YOUR BUSINESS.',
    frontLogo: 'MENANCE®',
    fabricGsm: 240,
    fabricType: 'Cotton Blend Waffle Knit',
    fit: 'Boxy Oversized',
    sleeveType: 'Full Sleeve',
    color: 'Black',
    description: '240 GSM Cotton blend thermal waffle knit with custom three-button placket. Engineered honeycomb weave provides textured insulation with an architectural, non-collapsing drape. Finished with "MIND YOUR BUSINESS." back quote and minimal front chest insignia.',
  },
  {
    id: 'prod_henley_offwhite',
    slug: 'the-henley-offwhite',
    name: 'The Henley — Off-White',
    category: 'Henleys',
    priceInr: 1899,
    priceUsd: 24,
    backQuote: 'NOT FOR EVERYONE.',
    frontLogo: 'MENANCE®',
    fabricGsm: 240,
    fabricType: 'Cotton Blend Waffle Knit',
    fit: 'Boxy Oversized',
    sleeveType: 'Full Sleeve',
    color: 'Off-White',
    description: '240 GSM Cotton blend waffle knit in raw natural off-white. Heavyweight drop-shoulder construction, custom tonal three-button placket, and ribbed wrist cuffs. Features signature distressed "NOT FOR EVERYONE." back typography.',
  },
  {
    id: 'prod_classic_black',
    slug: 'the-classic-waffle-black',
    name: 'The Classic Boxy Tee — Black',
    category: 'Tees',
    priceInr: 1699,
    priceUsd: 22,
    backQuote: 'SPEAK LESS. WEAR THIS.',
    frontLogo: 'MENANCE®',
    fabricGsm: 240,
    fabricType: '100% French Terry Cotton',
    fit: 'Boxy Oversized',
    sleeveType: 'Half Sleeve',
    color: 'Black',
    description: '240 GSM 100% French terry cotton heavy boxy tee. Thick 1.25" crew rib collar, elbow-length drop shoulder sleeves, and structured architectural drape. Screen printed "SPEAK LESS. WEAR THIS." across the upper back.',
  },
  {
    id: 'prod_classic_offwhite',
    slug: 'the-classic-waffle-offwhite',
    name: 'The Classic Boxy Tee — Off-White',
    category: 'Tees',
    priceInr: 1699,
    priceUsd: 22,
    backQuote: 'TAKE UP MORE SPACE.',
    frontLogo: 'MENANCE®',
    fabricGsm: 240,
    fabricType: '100% French Terry Cotton',
    fit: 'Boxy Oversized',
    sleeveType: 'Half Sleeve',
    color: 'Off-White',
    description: '240 GSM 100% French terry cotton in raw off-white. Heavyweight breathable knit with a boxy oversized cut, dropped shoulders, and statement "TAKE UP MORE SPACE." back print with discreet chest branding.',
  },
  {
    id: 'prod_acidwash_full',
    slug: 'acidwash-waffle-full',
    name: 'The Acidwash Tee — Half Sleeve',
    category: 'Heavyweight Tees',
    priceInr: 2199,
    priceUsd: 28,
    backQuote: 'LOOKS SOFT. ACTS HARD.',
    frontLogo: 'MENANCE®',
    fabricGsm: 240,
    fabricType: 'Mineral Acidwash Cotton',
    fit: 'Boxy Oversized',
    sleeveType: 'Half Sleeve',
    color: 'Acidwash Charcoal',
    description: '240 GSM custom mineral acidwash cotton with oversized boxy drape and relaxed half sleeves. Treated for a vintage broken-in patina. High-contrast back print: "LOOKS SOFT. ACTS HARD." with signature chest branding.',
  },
  {
    id: 'prod_heavy_black_full',
    slug: 'heavy-waffle-black-full',
    name: 'The Heavy Waffle — Black Full Sleeve',
    category: 'Waffle Full Sleeve',
    priceInr: 1999,
    priceUsd: 25,
    backQuote: 'MOVE DIFFERENT.',
    frontLogo: 'MENANCE®',
    fabricGsm: 240,
    fabricType: 'Cotton Blend Waffle Knit',
    fit: 'Boxy Oversized',
    sleeveType: 'Full Sleeve',
    color: 'Black',
    description: '240 GSM Cotton blend thermal waffle knit in pitch black. Drop shoulder silhouette with structured ribbing at neck and wrists. Emblazoned with "MOVE DIFFERENT." upper back stencil print.',
  },
  {
    id: 'prod_heavy_brown_full',
    slug: 'heavy-waffle-brown-full',
    name: 'The Heavy Waffle — Brown Full Sleeve',
    category: 'Waffle Full Sleeve',
    priceInr: 1999,
    priceUsd: 25,
    backQuote: 'NO EXPLANATIONS.',
    frontLogo: 'MENANCE®',
    fabricGsm: 240,
    fabricType: 'Cotton Blend Waffle Knit',
    fit: 'Boxy Oversized',
    sleeveType: 'Full Sleeve',
    color: 'Brown',
    description: '240 GSM Cotton blend thermal waffle knit in rich earth brown. Heavy textured drape, elongated sleeves, and raw streetwear silhouette. Features "NO EXPLANATIONS." back print and front MENANCE® branding.',
  },
  {
    id: 'prod_heavy_offwhite_full',
    slug: 'heavy-waffle-offwhite-full',
    name: 'The Heavy Waffle — Off-White Full Sleeve',
    category: 'Waffle Full Sleeve',
    priceInr: 1999,
    priceUsd: 25,
    backQuote: 'NOT FOR EVERYONE.',
    frontLogo: 'MENANCE®',
    fabricGsm: 240,
    fabricType: 'Cotton Blend Waffle Knit',
    fit: 'Boxy Oversized',
    sleeveType: 'Full Sleeve',
    color: 'Off-White',
    description: '240 GSM Cotton blend thermal waffle knit in raw optic off-white. Heavy honeycomb knit construction, dropped shoulders, and signature "NOT FOR EVERYONE." distressed back typography.',
  },
  {
    id: 'prod_striped_poplin_shirt',
    slug: 'the-striped-poplin-shirt',
    name: 'The Boxy Striped Oxford Shirt',
    category: 'Shirts',
    priceInr: 2299,
    priceUsd: 29,
    backQuote: 'TAKE UP MORE SPACE.',
    frontLogo: 'MENANCE®',
    fabricGsm: 160,
    fabricType: '100% Cotton Oxford',
    fit: 'Boxy Oversized',
    sleeveType: 'Half Sleeve',
    color: 'Sky Blue / White Stripe',
    description: '160 GSM 100% Cotton premium woven Oxford poplin short-sleeve shirt. Relaxed Cuban camp collar, dropped shoulders, boxy cut with vertical micro-pinstripes in sky blue and optic white. Back print: "TAKE UP MORE SPACE."',
  },
  {
    id: 'prod_red_gingham_shirt',
    slug: 'the-red-gingham-shirt',
    name: 'The Boxy Gingham Shirt — Crimson Red',
    category: 'Shirts',
    priceInr: 2299,
    priceUsd: 29,
    backQuote: 'SPEAK LESS. WEAR THIS.',
    frontLogo: 'MENANCE®',
    fabricGsm: 160,
    fabricType: '100% Cotton Oxford',
    fit: 'Boxy Oversized',
    sleeveType: 'Half Sleeve',
    color: 'Crimson Red / White Check',
    description: '160 GSM 100% Cotton Oxford short-sleeve button-down shirt. Clean structured camp collar, dropped shoulders, relaxed boxy cut with classic red and white micro-check pattern and "SPEAK LESS. WEAR THIS." back print.',
  },
  {
    id: 'prod_pink_gingham_shirt',
    slug: 'the-pink-gingham-shirt',
    name: 'The Boxy Gingham Shirt — Dusty Pink',
    category: 'Shirts',
    priceInr: 2299,
    priceUsd: 29,
    backQuote: 'NOT FOR EVERYONE.',
    frontLogo: 'MENANCE®',
    fabricGsm: 160,
    fabricType: '100% Cotton Oxford',
    fit: 'Boxy Oversized',
    sleeveType: 'Half Sleeve',
    color: 'Dusty Pink / White Check',
    description: '160 GSM 100% Cotton Oxford airy summer short-sleeve button-down. Relaxed camp collar, boxy drape, and subtle pastel pink gingham pattern with mother-of-pearl buttons and signature "NOT FOR EVERYONE." back typography.',
  },
  {
    id: 'prod_heavy_sweatpants_black',
    slug: 'heavy-wide-leg-sweatpants-black',
    name: 'The Heavy Boxy Fit Sweatpants — Black',
    category: 'Pants',
    priceInr: 2499,
    priceUsd: 32,
    backQuote: 'MOVE DIFFERENT.',
    frontLogo: 'MENANCE®',
    fabricGsm: 360,
    fabricType: '100% Cotton Heavy Fleece',
    fit: 'Wide Leg Boxy Fit',
    sleeveType: 'Full Length',
    color: 'Black',
    description: '360 GSM 100% Cotton ultra-heavyweight boxy fit lounge sweatpants. Wide cylindrical leg drape with zero stacking taper, heavy elastic waistband with extended matte metal-tipped drawstrings, and deep side welt pockets. Screen printed with "MOVE DIFFERENT." on the thigh.',
  },
  {
    id: 'prod_heavy_sweatpants_grey',
    slug: 'heavy-wide-leg-sweatpants-grey',
    name: 'The Cotton Lounge Joggers — Heather Grey',
    category: 'Pants',
    priceInr: 2499,
    priceUsd: 32,
    backQuote: 'LOOKS SOFT. ACTS HARD.',
    frontLogo: 'MENANCE®',
    fabricGsm: 290,
    fabricType: '100% Cotton Loopback Terry',
    fit: 'Wide Leg Baggy',
    sleeveType: 'Full Length',
    color: 'Heather Grey',
    description: '290 GSM 100% Cotton premium lounge joggers / wide-leg sweatpants. Zero stacking cylindrical drape, soft breathable loopback cotton interior with contrast black drawstrings and metal aglets. Features "LOOKS SOFT. ACTS HARD." distressed print.',
  },
  {
    id: 'prod_brown_boxy_tee',
    slug: 'brown-boxy-fit-tshirt',
    name: 'The Heavy French Terry Boxy Tee — Mocha Brown',
    category: 'Tees',
    priceInr: 1699,
    priceUsd: 22,
    backQuote: 'NO EXPLANATIONS.',
    frontLogo: 'MENANCE®',
    fabricGsm: 240,
    fabricType: '100% French Terry Cotton',
    fit: 'Boxy Oversized',
    sleeveType: 'Half Sleeve',
    color: 'Mocha Brown',
    description: '240 GSM 100% French terry cotton heavy boxy tee in vintage mocha brown. Dropped shoulders, relaxed raw streetwear drape, heavyweight collar rib, and signature "NO EXPLANATIONS." back print.',
  },
  {
    id: 'prod_offwhite_boxy_tee',
    slug: 'off-white-boxy-fit-tshirt',
    name: 'The Heavy French Terry Boxy Tee — Bone White',
    category: 'Tees',
    priceInr: 1699,
    priceUsd: 22,
    backQuote: 'TAKE UP MORE SPACE.',
    frontLogo: 'MENANCE®',
    fabricGsm: 240,
    fabricType: '100% French Terry Cotton',
    fit: 'Boxy Oversized',
    sleeveType: 'Half Sleeve',
    color: 'Bone White',
    description: '240 GSM 100% French terry cotton heavy boxy tee in raw bone white. Architectural drape that holds structure, finished with distressed "TAKE UP MORE SPACE." back quote.',
  },
];



