name = "menance-store"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "pk_test_ZmFpdGhmdWwtdGFkcG9sZS01MzYyLmNsZXJrLmFjY291bnRzLmRldiQ"
NEXT_PUBLIC_CLERK_SIGN_IN_URL = "/login"
NEXT_PUBLIC_CLERK_SIGN_UP_URL = "/signup"
NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL = "/account"
NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL = "/account"
ADMIN_EMAILS = "zamin@menance.store,admin@menance.store,zamin@menace.store,admin@menace.store,zaminaskari.work@gmail.com,askarizamin110@gmail.com"
PAYU_MERCHANT_KEY = "5AZJMt"
PAYU_MERCHANT_SALT = "7ieSYaBegBYUszannfMYuXpGJ7QBMlTp"
PAYU_MERCHANT_ID = "13779004"
PAYU_CLIENT_ID = "fba7ab236b106dc64bbb3e79af571e91c70c810c82092884fb9b932470270a56"
PAYU_CLIENT_SECRET = "96c95faae059ad654cb59b0c12efa4865d18809e570e9fdffe018b049707337b"
PAYU_MODE = "live"
NEXT_PUBLIC_PAYU_KEY = "5AZJMt"
NEXT_PUBLIC_PAYU_MODE = "live"
RESEND_FROM_EMAIL = "MENANCE <orders@wearmenance.in>"

[[d1_databases]]
binding = "DB"
database_name = "menace-db"
database_id = "5208d6ac-b7b7-41d2-bcd6-2a7a4962c8b0"
migrations_dir = "src/lib/db/migrations"

[[kv_namespaces]]
binding = "MENACE_KV"
id = "ab2dd890e2774b26a4b088482abeceef"
